'use client';

import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const translations = {
  fr: {
    navAbout:'À propos', navExperience:'Expérience', navProjects:'Projets', navAwards:'Distinctions', navCyber:'Cyber', navCerts:'Certifications', navEducation:'Diplômes', navContact:'Contact',
    language:'Langue',
    heroRole:'Ingénieur systèmes embarqués & Safety',
    heroBio:'Ingénieur en systèmes embarqués et sûreté de fonctionnement, j’ai évolué du développement électronique et logiciel vers la sûreté automobile et ferroviaire. Aujourd’hui, je me spécialise en cybersécurité afin de mettre cette expérience au service de la protection des systèmes d’information.',
    heroIntro:'Ingénieur systèmes embarqués & Safety, actuellement en reconversion vers la cybersécurité.',
    contactMe:'Me contacter', downloadCv:'Télécharger mon CV', keyFigures:'Chiffres clés', yearsExp:'Années d’expérience', projects:'Projets techniques', awards:'Prix & distinctions', certifications:'Certifications', keyDomains:'Domaines clés', domains:'Systèmes embarqués · Sûreté de fonctionnement · Cybersécurité', career:'PARCOURS', professionalExp:'Expériences professionnelles', looking:'À la recherche', apprenticeship:'D’une alternance en cybersécurité', internships:'Stages',
    available:'Disponible pour une alternance en cybersécurité',
    about:'À PROPOS', aboutTitle:'Un parcours technique construit autour des systèmes critiques.', aboutP1:'Diplômé en génie électrique et systèmes embarqués, puis titulaire d’un Master 2 en Ingénierie des Systèmes Temps Réel, j’ai évolué de la conception embarquée vers la sûreté de fonctionnement automobile et ferroviaire.', aboutP2:'Mes expériences m’ont amené à travailler sur des systèmes connectés, des protocoles de communication, l’automatisation des tests, la traçabilité d’exigences Safety et l’analyse de défaillances. Aujourd’hui, je réalise une reconversion vers la cybersécurité afin de mettre cette rigueur d’ingénieur au service de la protection des systèmes d’information, des réseaux et des infrastructures.',
    cyberLabel:'RECONVERSION VERS LA CYBERSÉCURITÉ', cyberTitle:'De la sûreté des systèmes à la protection des systèmes d’information.', cyberCopy:'Mon parcours d’ingénieur m’a appris à analyser des systèmes complexes, identifier les défaillances, vérifier la conformité et travailler avec des environnements critiques. Je transpose aujourd’hui cette rigueur vers la cybersécurité en développant mes compétences en analyse réseau, SIEM, gestion des incidents, Linux, Windows Server, Active Directory et sécurité des infrastructures.', observe:'Observer', detect:'Détecter', analyse:'Analyser', respond:'Répondre', cyberCaption:'Comprendre, détecter et réduire les risques pour protéger les systèmes et les données.',
    educationLabel:'FORMATION', degrees:'Diplômes', nexaBul1:'Formation en cybersécurité avec rythme d’alternance : 3 semaines en entreprise / 1 semaine à l’école.', nexaBul2:'Développement de compétences en sécurité des systèmes, réseaux, supervision et gestion des incidents.', nexaBul3:'Approfondissement de Linux, Windows Server, Active Directory, SIEM et analyse réseau.', interests:'CENTRES D’INTÉRÊT', outside:'En dehors du travail', cyberWatch:'Veille cybersécurité', travel:'Voyage',
    contactLabel:'CONTACT', contactTitle:'Construisons la prochaine étape.', contactCopy:'Je recherche une alternance en cybersécurité dès septembre 2026 et je reste ouvert aux échanges autour de la sécurité des systèmes, des réseaux, du SOC, de l’embarqué et de la sûreté de fonctionnement.', emailLabel:'ME CONTACTER PAR E-MAIL', sendMessage:'Envoyez-moi un message', yourEmail:'Votre e-mail', subject:'Objet', description:'Description', send:'Envoyer le message', sending:'Envoi en cours…',
    opportunity:'OPPORTUNITÉ RECHERCHÉE', altCyber:'Alternance Cybersécurité', altText:'Disponible dès septembre 2026 pour une alternance en cybersécurité, avec un rythme de 3 semaines en entreprise / 1 semaine à l’école.'
  },
  en: {
    navAbout:'About', navExperience:'Experience', navProjects:'Projects', navAwards:'Awards', navCyber:'Cyber', navCerts:'Certifications', navEducation:'Education', navContact:'Contact', language:'Language',
    heroRole:'Embedded Systems & Safety Engineer', heroBio:'Embedded systems and functional safety engineer with experience spanning electronic/software development, automotive safety and railway safety. I am now specialising in cybersecurity to apply this background to protecting information systems.', heroIntro:'Embedded Systems & Safety Engineer currently transitioning into cybersecurity.', contactMe:'Contact me', downloadCv:'Download my CV', keyFigures:'Key figures', yearsExp:'Years of experience', projects:'Technical projects', awards:'Awards & distinctions', certifications:'Certifications', keyDomains:'Key domains', domains:'Embedded systems · Functional safety · Cybersecurity', career:'CAREER', professionalExp:'Professional experience', looking:'Looking for', apprenticeship:'A cybersecurity apprenticeship', internships:'Internships', available:'Available for a cybersecurity apprenticeship',
    about:'ABOUT', aboutTitle:'A technical career built around critical systems.', aboutP1:'With an engineering degree in electrical engineering and embedded systems, followed by a Master 2 in Real-Time Systems Engineering, I moved from embedded development to automotive and railway functional safety.', aboutP2:'My experience includes connected systems, communication protocols, test automation, Safety requirements traceability and failure analysis. I am now transitioning into cybersecurity to apply this engineering rigor to protecting information systems, networks and infrastructure.',
    cyberLabel:'TRANSITION TO CYBERSECURITY', cyberTitle:'From system safety to information-system protection.', cyberCopy:'My engineering background taught me how to analyse complex systems, identify failures, verify compliance and work in critical environments. I now apply that rigor to cybersecurity while developing skills in network analysis, SIEM, incident management, Linux, Windows Server, Active Directory and infrastructure security.', observe:'Observe', detect:'Detect', analyse:'Analyse', respond:'Respond', cyberCaption:'Understand, detect and reduce risks to protect systems and data.',
    educationLabel:'EDUCATION', degrees:'Degrees', nexaBul1:'Cybersecurity programme with an apprenticeship rhythm: 3 weeks in company / 1 week at school.', nexaBul2:'Skills development in system security, networks, monitoring and incident management.', nexaBul3:'Advanced work with Linux, Windows Server, Active Directory, SIEM and network analysis.', interests:'INTERESTS', outside:'Outside work', cyberWatch:'Cybersecurity watch', travel:'Travel',
    contactLabel:'CONTACT', contactTitle:'Let’s build the next step.', contactCopy:'I am looking for a cybersecurity apprenticeship from September 2026 and remain open to discussions around system security, networks, SOC, embedded systems and functional safety.', emailLabel:'CONTACT ME BY EMAIL', sendMessage:'Send me a message', yourEmail:'Your email', subject:'Subject', description:'Description', send:'Send message', sending:'Sending…', opportunity:'OPPORTUNITY WANTED', altCyber:'Cybersecurity Apprenticeship', altText:'Available from September 2026 for a cybersecurity apprenticeship, with a rhythm of 3 weeks in company / 1 week at school.'
  },
  ar: {
    navAbout:'نبذة عني', navExperience:'الخبرات', navProjects:'المشاريع', navAwards:'الجوائز', navCyber:'الأمن السيبراني', navCerts:'الشهادات', navEducation:'الدراسة', navContact:'التواصل', language:'اللغة',
    heroRole:'مهندس أنظمة مدمجة وسلامة وظيفية', heroBio:'مهندس في الأنظمة المدمجة والسلامة الوظيفية، انتقلت من تطوير الإلكترونيات والبرمجيات إلى السلامة في قطاعي السيارات والسكك الحديدية. أتخصص حالياً في الأمن السيبراني لتوظيف هذه الخبرة في حماية أنظمة المعلومات.', heroIntro:'مهندس أنظمة مدمجة وسلامة وظيفية، في مرحلة انتقال مهني نحو الأمن السيبراني.', contactMe:'تواصل معي', downloadCv:'تحميل السيرة الذاتية', keyFigures:'أرقام رئيسية', yearsExp:'سنوات خبرة', projects:'مشاريع تقنية', awards:'جوائز وتميّز', certifications:'شهادات', keyDomains:'مجالات رئيسية', domains:'الأنظمة المدمجة · السلامة الوظيفية · الأمن السيبراني', career:'المسار المهني', professionalExp:'الخبرات المهنية', looking:'أبحث عن', apprenticeship:'تدريب بالتناوب في الأمن السيبراني', internships:'تدريبات', available:'متاح لتدريب بالتناوب في الأمن السيبراني',
    about:'نبذة عني', aboutTitle:'مسار تقني مبني حول الأنظمة الحرجة.', aboutP1:'بعد حصولي على دبلوم هندسة في الهندسة الكهربائية والأنظمة المدمجة ثم ماستر 2 في هندسة الأنظمة ذات الزمن الحقيقي، انتقلت من التصميم المدمج إلى السلامة الوظيفية في السيارات والسكك الحديدية.', aboutP2:'أتاحت لي خبراتي العمل على الأنظمة المتصلة، بروتوكولات الاتصال، أتمتة الاختبارات، تتبع متطلبات السلامة وتحليل الأعطال. أتحول اليوم نحو الأمن السيبراني لتوظيف هذه الصرامة الهندسية في حماية أنظمة المعلومات والشبكات والبنى التحتية.',
    cyberLabel:'الانتقال نحو الأمن السيبراني', cyberTitle:'من سلامة الأنظمة إلى حماية أنظمة المعلومات.', cyberCopy:'علّمني مساري الهندسي تحليل الأنظمة المعقدة، تحديد الأعطال، التحقق من المطابقة والعمل في البيئات الحرجة. أوظف اليوم هذه الصرامة في الأمن السيبراني مع تطوير مهاراتي في تحليل الشبكات وSIEM وإدارة الحوادث وLinux وWindows Server وActive Directory وأمن البنى التحتية.', observe:'المراقبة', detect:'الكشف', analyse:'التحليل', respond:'الاستجابة', cyberCaption:'فهم المخاطر وكشفها وتقليلها لحماية الأنظمة والبيانات.',
    educationLabel:'التكوين', degrees:'الشهادات الأكاديمية', nexaBul1:'تكوين في الأمن السيبراني بنظام تناوب: 3 أسابيع في الشركة / أسبوع واحد في المدرسة.', nexaBul2:'تطوير مهارات في أمن الأنظمة والشبكات والمراقبة وإدارة الحوادث.', nexaBul3:'تعميق المهارات في Linux وWindows Server وActive Directory وSIEM وتحليل الشبكات.', interests:'الاهتمامات', outside:'خارج العمل', cyberWatch:'متابعة الأمن السيبراني', travel:'السفر',
    contactLabel:'التواصل', contactTitle:'لنَبْنِ الخطوة القادمة.', contactCopy:'أبحث عن تدريب بالتناوب في الأمن السيبراني ابتداءً من سبتمبر 2026، وأنا منفتح على فرص مرتبطة بأمن الأنظمة والشبكات وSOC والأنظمة المدمجة والسلامة الوظيفية.', emailLabel:'التواصل عبر البريد الإلكتروني', sendMessage:'أرسل لي رسالة', yourEmail:'بريدك الإلكتروني', subject:'الموضوع', description:'الوصف', send:'إرسال الرسالة', sending:'جارٍ الإرسال…', opportunity:'الفرصة المطلوبة', altCyber:'تدريب بالتناوب في الأمن السيبراني', altText:'متاح ابتداءً من سبتمبر 2026 لتدريب بالتناوب في الأمن السيبراني، بنظام 3 أسابيع في الشركة / أسبوع واحد في المدرسة.'
  },
  es: {
    navAbout:'Sobre mí', navExperience:'Experiencia', navProjects:'Proyectos', navAwards:'Premios', navCyber:'Ciberseguridad', navCerts:'Certificaciones', navEducation:'Formación', navContact:'Contacto', language:'Idioma',
    heroRole:'Ingeniero de Sistemas Embebidos y Safety', heroBio:'Ingeniero de sistemas embebidos y seguridad funcional, con experiencia desde el desarrollo electrónico y software hasta la seguridad automotriz y ferroviaria. Actualmente me especializo en ciberseguridad para aplicar esta experiencia a la protección de los sistemas de información.', heroIntro:'Ingeniero de Sistemas Embebidos y Safety, actualmente en transición hacia la ciberseguridad.', contactMe:'Contactarme', downloadCv:'Descargar mi CV', keyFigures:'Datos clave', yearsExp:'Años de experiencia', projects:'Proyectos técnicos', awards:'Premios y distinciones', certifications:'Certificaciones', keyDomains:'Áreas clave', domains:'Sistemas embebidos · Seguridad funcional · Ciberseguridad', career:'TRAYECTORIA', professionalExp:'Experiencia profesional', looking:'Buscando', apprenticeship:'Una alternancia en ciberseguridad', internships:'Prácticas', available:'Disponible para una alternancia en ciberseguridad',
    about:'SOBRE MÍ', aboutTitle:'Una trayectoria técnica construida alrededor de sistemas críticos.', aboutP1:'Titulado en ingeniería eléctrica y sistemas embebidos, y posteriormente con un Máster 2 en Ingeniería de Sistemas de Tiempo Real, evolucioné del desarrollo embebido hacia la seguridad funcional automotriz y ferroviaria.', aboutP2:'Mis experiencias me han llevado a trabajar con sistemas conectados, protocolos de comunicación, automatización de pruebas, trazabilidad de requisitos Safety y análisis de fallos. Hoy realizo una transición hacia la ciberseguridad para aplicar este rigor de ingeniería a la protección de sistemas de información, redes e infraestructuras.',
    cyberLabel:'TRANSICIÓN HACIA LA CIBERSEGURIDAD', cyberTitle:'De la seguridad de los sistemas a la protección de los sistemas de información.', cyberCopy:'Mi experiencia como ingeniero me enseñó a analizar sistemas complejos, identificar fallos, verificar la conformidad y trabajar en entornos críticos. Hoy traslado este rigor a la ciberseguridad desarrollando competencias en análisis de redes, SIEM, gestión de incidentes, Linux, Windows Server, Active Directory y seguridad de infraestructuras.', observe:'Observar', detect:'Detectar', analyse:'Analizar', respond:'Responder', cyberCaption:'Comprender, detectar y reducir los riesgos para proteger los sistemas y los datos.',
    educationLabel:'FORMACIÓN', degrees:'Títulos', nexaBul1:'Formación en ciberseguridad con ritmo de alternancia: 3 semanas en empresa / 1 semana en la escuela.', nexaBul2:'Desarrollo de competencias en seguridad de sistemas, redes, monitorización y gestión de incidentes.', nexaBul3:'Profundización en Linux, Windows Server, Active Directory, SIEM y análisis de redes.', interests:'INTERESES', outside:'Fuera del trabajo', cyberWatch:'Vigilancia de ciberseguridad', travel:'Viajes',
    contactLabel:'CONTACTO', contactTitle:'Construyamos la próxima etapa.', contactCopy:'Busco una alternancia en ciberseguridad a partir de septiembre de 2026 y estoy abierto a oportunidades relacionadas con seguridad de sistemas, redes, SOC, sistemas embebidos y seguridad funcional.', emailLabel:'CONTACTARME POR EMAIL', sendMessage:'Envíame un mensaje', yourEmail:'Tu email', subject:'Asunto', description:'Descripción', send:'Enviar mensaje', sending:'Enviando…', opportunity:'OPORTUNIDAD BUSCADA', altCyber:'Alternancia en Ciberseguridad', altText:'Disponible desde septiembre de 2026 para una alternancia en ciberseguridad, con un ritmo de 3 semanas en empresa / 1 semana en la escuela.'
  },
  de: {
    navAbout:'Über mich', navExperience:'Erfahrung', navProjects:'Projekte', navAwards:'Auszeichnungen', navCyber:'Cybersecurity', navCerts:'Zertifikate', navEducation:'Ausbildung', navContact:'Kontakt', language:'Sprache',
    heroRole:'Ingenieur für Embedded Systems & Safety', heroBio:'Ingenieur für Embedded Systems und funktionale Sicherheit mit Erfahrung von Elektronik- und Softwareentwicklung bis zur Safety im Automobil- und Bahnsektor. Heute spezialisiere ich mich auf Cybersecurity, um diese Erfahrung zum Schutz von Informationssystemen einzusetzen.', heroIntro:'Ingenieur für Embedded Systems & Safety, derzeit im Übergang zur Cybersecurity.', contactMe:'Kontakt', downloadCv:'Lebenslauf herunterladen', keyFigures:'Kennzahlen', yearsExp:'Jahre Erfahrung', projects:'Technische Projekte', awards:'Preise & Auszeichnungen', certifications:'Zertifikate', keyDomains:'Kernbereiche', domains:'Embedded Systems · Funktionale Sicherheit · Cybersecurity', career:'KARRIERE', professionalExp:'Berufserfahrung', looking:'Auf der Suche', apprenticeship:'Nach einer Cybersecurity-Ausbildung im Wechselmodell', internships:'Praktika', available:'Verfügbar für eine Cybersecurity-Ausbildung im Wechselmodell',
    about:'ÜBER MICH', aboutTitle:'Ein technischer Werdegang rund um kritische Systeme.', aboutP1:'Nach meinem Ingenieurabschluss in Elektrotechnik und Embedded Systems sowie einem Master 2 in Echtzeitsystemtechnik entwickelte ich mich von der Embedded-Entwicklung hin zur funktionalen Sicherheit im Automobil- und Bahnsektor.', aboutP2:'Meine Erfahrungen umfassen vernetzte Systeme, Kommunikationsprotokolle, Testautomatisierung, Nachverfolgbarkeit von Safety-Anforderungen und Fehleranalysen. Heute wechsle ich in die Cybersecurity, um diese technische Sorgfalt zum Schutz von Informationssystemen, Netzwerken und Infrastrukturen einzusetzen.',
    cyberLabel:'WECHSEL ZUR CYBERSECURITY', cyberTitle:'Von Systemsicherheit zum Schutz von Informationssystemen.', cyberCopy:'Mein technischer Hintergrund hat mich gelehrt, komplexe Systeme zu analysieren, Fehler zu identifizieren, Konformität zu prüfen und in kritischen Umgebungen zu arbeiten. Diese Sorgfalt übertrage ich heute auf die Cybersecurity und vertiefe meine Kenntnisse in Netzwerkanalyse, SIEM, Incident Management, Linux, Windows Server, Active Directory und Infrastruktursicherheit.', observe:'Beobachten', detect:'Erkennen', analyse:'Analysieren', respond:'Reagieren', cyberCaption:'Risiken verstehen, erkennen und reduzieren, um Systeme und Daten zu schützen.',
    educationLabel:'AUSBILDUNG', degrees:'Abschlüsse', nexaBul1:'Cybersecurity-Ausbildung im Wechselmodell: 3 Wochen im Unternehmen / 1 Woche in der Schule.', nexaBul2:'Kompetenzaufbau in Systemsicherheit, Netzwerken, Monitoring und Incident Management.', nexaBul3:'Vertiefung in Linux, Windows Server, Active Directory, SIEM und Netzwerkanalyse.', interests:'INTERESSEN', outside:'Außerhalb der Arbeit', cyberWatch:'Cybersecurity-Beobachtung', travel:'Reisen',
    contactLabel:'KONTAKT', contactTitle:'Gestalten wir den nächsten Schritt.', contactCopy:'Ich suche ab September 2026 eine Cybersecurity-Ausbildung im Wechselmodell und bin offen für Gespräche zu Systemsicherheit, Netzwerken, SOC, Embedded Systems und funktionaler Sicherheit.', emailLabel:'KONTAKT PER E-MAIL', sendMessage:'Nachricht senden', yourEmail:'Ihre E-Mail', subject:'Betreff', description:'Beschreibung', send:'Nachricht senden', sending:'Wird gesendet…', opportunity:'GESUCHTE MÖGLICHKEIT', altCyber:'Cybersecurity-Ausbildung', altText:'Ab September 2026 verfügbar für eine Cybersecurity-Ausbildung im Wechselmodell mit 3 Wochen im Unternehmen / 1 Woche in der Schule.'
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('fr');

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (key) => translations[language]?.[key] ?? translations.fr[key] ?? key,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
}
